# Generated by Django 4.2.20 on 2025-04-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exercises', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
