# Generated by Django 4.2.20 on 2025-05-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_userexercise_exercise_alter_userexercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_images/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('Gögüs', 'Gögüs'), ('Sirt', 'Sirt'), ('Bacak', 'Bacak'), ('Omuz', 'Omuz'), ('Kollar', 'Kollar'), ('Karin', 'Karin')], default='Gögüs', max_length=20),
        ),
    ]
